#!/usr/bin/env python3
"""Generates the static sub-pages of the Klimat OK site.

  klimat-ok/<service-slug>/index.html   ← content_services.py
  klimat-ok/blog/index.html             ← content_blog.py
  klimat-ok/blog/<post-slug>/index.html ← content_blog.py

The home page (klimat-ok/index.html) is hand-written. Shared chrome (top bar,
header, footer, floating CTAs, drawer) lives here, so change it in one place.

Run:  python3 klimat-ok/_build/build_pages.py
"""
import html
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from content_services import ICONS, SERVICES  # noqa: E402
from content_blog import POSTS, UPCOMING  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PHONE = '518 353 169'
TEL = 'tel:518353169'
MAIL = 'klimat.ok@vp.pl'
CHIPS = ['Mieszkanie', 'Dom', 'Biuro / lokal', 'Serwis']
BUSINESS = {'@type': 'HVACBusiness', 'name': 'Klimat OK', 'telephone': '+48518353169', 'email': MAIL,
            'address': {'@type': 'PostalAddress', 'streetAddress': 'Poranna 43', 'postalCode': '53-026',
                        'addressLocality': 'Wrocław', 'addressCountry': 'PL'}}
e = html.escape


# ---------------------------------------------------------------- chrome ----

def head(r, title, desc, og_img, ld, preload=None):
    pre = f'\n  <link rel="preload" as="image" href="{preload}">' if preload else ''
    return f'''<!doctype html>
<!-- Generated by _build/build_pages.py — edit the content files there, not this file. -->
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>{e(title)}</title>
  <meta name="description" content="{e(desc)}">
  <meta name="theme-color" content="#0B1220">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="pl_PL">
  <meta property="og:title" content="{e(title)}">
  <meta property="og:description" content="{e(desc)}">
  <meta property="og:image" content="{og_img}">
  <link rel="icon" href="{r}assets/img/favicon.svg" type="image/svg+xml">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700;800&family=IBM+Plex+Sans:wght@400;500;600&display=swap" rel="stylesheet">{pre}
  <link rel="stylesheet" href="{r}css/styles.css">
  <script>document.documentElement.classList.add('js');</script>
  <script type="application/ld+json">
{json.dumps(ld, ensure_ascii=False, indent=2)}
  </script>
</head>
<body data-form-endpoint="">
  <a class="skip-link" href="#main">Przejdź do treści</a>
'''


def header(r, active):
    def link(key, href, label):
        cls = 'nav__link is-active' if key == active else 'nav__link'
        return f'        <a href="{href}" class="{cls}">{label}</a>'
    nav = '\n'.join([
        link('uslugi', f'{r}#uslugi', 'Usługi'),
        link('proces', f'{r}#proces', 'Jak pracujemy'),
        link('realizacje', f'{r}#realizacje', 'Realizacje'),
        link('opinie', f'{r}#opinie', 'Opinie'),
        link('blog', f'{r}blog/', 'Blog'),
        link('faq', f'{r}#faq', 'FAQ'),
        link('kontakt', '#kontakt', 'Kontakt'),
    ])
    return f'''
  <div class="topbar">
    <div class="container topbar__inner">
      <span>Klimatyzacja • montaż • serwis | Wrocław i okolice</span>
      <a href="mailto:{MAIL}" class="topbar__mail">{MAIL}</a>
      <a href="{TEL}" class="topbar__tel">{PHONE}</a>
    </div>
  </div>

  <header class="header" id="header">
    <div class="container header__inner">
      <a href="{r}" class="header__logo" aria-label="Klimat OK — strona główna">
        <img src="{r}assets/img/logo.png" alt="Klimat OK" width="640" height="116">
      </a>
      <nav class="nav" aria-label="Główna nawigacja">
{nav}
      </nav>
      <a href="#kontakt" class="btn btn--primary btn--sm header__cta">Poproś o wycenę</a>
      <a href="{TEL}" class="header__phone">{PHONE}</a>
      <button class="burger" type="button" aria-label="Menu" aria-expanded="false" aria-controls="drawer">
        <span></span><span></span><span></span>
      </button>
    </div>
  </header>
'''


def chips(active):
    return '\n                  '.join(
        f'<button type="button" class="chip{" is-active" if i == active else ""}" role="radio" '
        f'aria-checked="{"true" if i == active else "false"}">{c}</button>'
        for i, c in enumerate(CHIPS))


def hero_form(service, chip, note):
    return f'''
        <div class="quote-card only-desk" data-anim="card">
          <div class="quote-card__head">
            <h2>Poproś o wycenę</h2>
            <p>{note}</p>
          </div>
          <div class="quote-card__body">
            <form class="lead-form" data-form="hero" data-service="{service}" novalidate>
              <fieldset class="chips-field">
                <legend class="field-label">Czego dotyczy zapytanie?</legend>
                <div class="chips" role="radiogroup">
                  {chips(chip)}
                </div>
              </fieldset>
              <div class="form-row">
                <div class="field">
                  <label for="hero-imie" class="field-label">Imię</label>
                  <input id="hero-imie" name="imie" placeholder="Jan" autocomplete="given-name" required>
                  <span class="field-error">Podaj imię</span>
                </div>
                <div class="field">
                  <label for="hero-tel" class="field-label">Telefon</label>
                  <input id="hero-tel" name="telefon" type="tel" placeholder="500 100 200" autocomplete="tel" inputmode="tel" required>
                  <span class="field-error">Podaj poprawny numer</span>
                </div>
              </div>
              <div class="field">
                <label for="hero-msg" class="field-label">Wiadomość (opcjonalnie)</label>
                <textarea id="hero-msg" name="wiadomosc" rows="2" placeholder="Czego dotyczy zapytanie?"></textarea>
              </div>
              <button type="submit" class="btn btn--primary btn--block btn--submit">Poproś o wycenę</button>
              <p class="form-note">Skontaktujemy się w sprawie Twojego zapytania.</p>
            </form>
            {SUCCESS}
          </div>
        </div>'''


SUCCESS = '''<div class="form-success" hidden>
              <svg class="form-success__icon" viewBox="0 0 52 52" aria-hidden="true"><circle cx="26" cy="26" r="24"/><path d="M15 27 l7.5 7.5 L37 19"/></svg>
              <h3>Dziękujemy. Twoje zapytanie zostało wysłane.</h3>
              <p>Skontaktujemy się w sprawie zgłoszenia.</p>
            </div>'''

PROOF = f'''
          <div class="hero__proof" data-anim="5">
            <div class="rating">
              <div class="rating__score" data-count="5,0">5,0</div>
              <div class="rating__meta">
                <div class="stars" aria-label="5 na 5 gwiazdek">★★★★★</div>
                <div class="rating__txt"><strong><span data-count="359">359</span> opinii</strong> w Google</div>
              </div>
            </div>
            <div class="hero__divider only-desk" aria-hidden="true"></div>
            <div class="hero__brands">Mitsubishi · LG · KAISAI<br class="br-desk"><span class="only-mob"> · </span>Cooper &amp; Hunter · Toshiba</div>
          </div>'''


def contact(r, service='', chip=0, placeholder='Montaż, serwis, przegląd, dobór urządzenia…'):
    return f'''
    <section class="contact" id="kontakt">
      <img class="contact__bg" src="{r}assets/img/band.jpg" alt="" loading="lazy" width="1080" height="1080">
      <div class="contact__shade" aria-hidden="true"></div>
      <div class="container contact__grid">
        <div class="contact__copy" data-reveal>
          <h2 class="contact__title">Poproś o wycenę</h2>
          <p class="contact__lead"><span class="only-desk">Skontaktuj się z Klimat OK i opowiedz, czego potrzebujesz. Pomożemy dobrać odpowiednie rozwiązanie i ustalić zakres realizacji.</span><span class="only-mob">Skontaktuj się z Klimat OK i opowiedz, czego potrzebujesz.</span></p>
          <a href="{TEL}" class="btn btn--white contact__phone">{PHONE}</a>
          <div class="contact__meta">
            <a href="mailto:{MAIL}">{MAIL}</a>
            <span>Poranna 43, 53-026 Wrocław</span>
          </div>
        </div>
        <div class="contact-card" data-reveal>
          <form class="lead-form" data-form="contact" data-service="{service}" novalidate>
            <h3 class="contact-card__title only-desk">Formularz kontaktowy</h3>
            <fieldset class="chips-field only-mob">
              <legend class="field-label">Czego dotyczy zapytanie?</legend>
              <div class="chips" role="radiogroup">
                {chips(chip)}
              </div>
            </fieldset>
            <div class="field">
              <label for="k-imie" class="field-label">Imię</label>
              <input id="k-imie" name="imie" placeholder="Jan" autocomplete="given-name" required>
              <span class="field-error">Podaj imię</span>
            </div>
            <div class="field">
              <label for="k-tel" class="field-label">Telefon</label>
              <input id="k-tel" name="telefon" type="tel" placeholder="500 100 200" autocomplete="tel" inputmode="tel" required>
              <span class="field-error">Podaj poprawny numer</span>
            </div>
            <div class="field">
              <label for="k-msg" class="field-label">Wiadomość<span class="only-mob"> (opcjonalnie)</span></label>
              <textarea id="k-msg" name="wiadomosc" rows="3" placeholder="{e(placeholder)}" data-placeholder-mob="Czego dotyczy zapytanie?"></textarea>
            </div>
            <button type="submit" class="btn btn--dark btn--block btn--submit btn--contact">Wyślij zapytanie</button>
            <p class="form-note">Skontaktujemy się w sprawie Twojego zapytania.</p>
          </form>
          {SUCCESS}
        </div>
        <div class="contact__meta-mob only-mob">
          <a href="{TEL}" class="contact__phone-mob">{PHONE}</a>
          <a href="mailto:{MAIL}">{MAIL}</a>
          <span>Poranna 43, 53-026 Wrocław</span>
        </div>
      </div>
    </section>'''


def footer(r, active):
    services = '\n'.join(f'        <a href="{r}{s["slug"]}/">{e(s["name"])}</a>' for s in SERVICES)
    drawer_items = [
        ('home', r, 'Strona główna'), ('uslugi', f'{r}#uslugi', 'Usługi'), ('proces', f'{r}#proces', 'Jak pracujemy'),
        ('realizacje', f'{r}#realizacje', 'Realizacje'), ('opinie', f'{r}#opinie', 'Opinie'),
        ('blog', f'{r}blog/', 'Blog'), ('faq', f'{r}#faq', 'FAQ'), ('kontakt', '#kontakt', 'Kontakt'),
    ]
    drawer = '\n'.join(
        '        <a href="{}" data-close{}>{}</a>'.format(href, ' class="is-active"' if key == active else '', label)
        for key, href, label in drawer_items)
    return f'''
  <footer class="footer">
    <div class="container footer__grid">
      <div class="footer__brand">
        <div class="footer__logo"><img src="{r}assets/img/logo.png" alt="Klimat OK" width="640" height="116" loading="lazy"></div>
        <p>Sprzedaż, montaż i serwis klimatyzacji. Wrocław i Dolny Śląsk.</p>
      </div>
      <div class="footer__col">
        <span class="footer__head">Kontakt</span>
        <a href="{TEL}">{PHONE}</a>
        <a href="mailto:{MAIL}">{MAIL}</a>
        <span>Poranna 43, 53-026 Wrocław</span>
        <span>NIP 825 216 41 07</span>
        <span>REGON 360875870</span>
      </div>
      <div class="footer__col only-desk">
        <span class="footer__head">Usługi</span>
{services}
        <a href="{r}blog/">Blog</a>
      </div>
      <div class="footer__col">
        <span class="footer__head">Obszar działania</span>
        <span class="only-desk">Wrocław i Dolny Śląsk</span>
        <span class="only-desk">Wrocław + 100 km</span>
        <span class="only-desk">Oława</span>
        <span class="only-desk">Siechnice</span>
        <span class="only-mob">Wrocław i Dolny Śląsk · Wrocław + 100 km · Oława · Siechnice</span>
      </div>
    </div>
    <div class="container footer__bottom">© <span data-year>2026</span> Klimat OK</div>
  </footer>

  <div class="dock" aria-hidden="true">
    <div class="dock__card">
      <a href="{TEL}" class="btn btn--dark btn--dock" tabindex="-1">Zadzwoń</a>
      <a href="#kontakt" class="btn btn--primary btn--dock btn--pulse" tabindex="-1">Poproś o wycenę</a>
    </div>
  </div>

  <div class="mbar">
    <a href="{TEL}" class="btn btn--dark">Zadzwoń</a>
    <a href="#kontakt" class="btn btn--primary btn--pulse">Poproś o wycenę</a>
  </div>

  <div class="drawer" id="drawer" aria-hidden="true">
    <div class="drawer__backdrop" data-close></div>
    <div class="drawer__panel" role="dialog" aria-modal="true" aria-label="Menu">
      <div class="drawer__top">
        <span class="drawer__title">Menu</span>
        <button type="button" class="drawer__close" data-close aria-label="Zamknij menu">×</button>
      </div>
      <nav class="drawer__nav">
{drawer}
      </nav>
      <div class="drawer__foot">
        <a href="{TEL}" class="btn btn--primary btn--block" data-close>{PHONE}</a>
        <a href="mailto:{MAIL}" class="drawer__mail">{MAIL}</a>
      </div>
    </div>
  </div>

  <div class="lightbox" hidden>
    <button type="button" class="lightbox__close" aria-label="Zamknij">×</button>
    <img alt="">
  </div>

  <script src="{r}js/main.js" defer></script>
</body>
</html>
'''


def crumbs(items):
    """items: list of (label, href or None)."""
    lis = []
    for label, href in items:
        lis.append(f'<li><a href="{href}">{e(label)}</a></li>' if href else f'<li><span aria-current="page">{e(label)}</span></li>')
    return '<ol class="crumbs" data-anim="1" aria-label="Okruszki">\n            ' + '\n            '.join(lis) + '\n          </ol>'


def breadcrumb_ld(items):
    return {'@context': 'https://schema.org', '@type': 'BreadcrumbList', 'itemListElement': [
        dict({'@type': 'ListItem', 'position': i + 1, 'name': label}, **({'item': href} if href else {}))
        for i, (label, href) in enumerate(items)]}


def icon(name):
    return f'<svg viewBox="0 0 24 24" aria-hidden="true">{ICONS[name]}</svg>'


def blocks_html(blocks):
    """Content blocks → plain editor markup (what the WordPress block editor outputs)."""
    parts = []
    for b in blocks:
        if isinstance(b, dict):
            parts.append('<ul>\n' + '\n'.join(f'  <li>{t}</li>' for t in b['checks']) + '\n</ul>')
        else:
            parts.append(f'<p>{b}</p>')
    return '\n'.join(parts)


def entry_content(intro, sections, extra=''):
    """The body as it would come from the_content(): intro paragraph + h2 sections."""
    body = [f'<p>{intro}</p>']
    for title, blocks in sections:
        body.append(f'<h2>{title}</h2>')
        body.append(blocks_html(blocks))
    if extra:
        body.append(extra)
    inner = '\n'.join(body).replace('\n', '\n          ')
    return f'<div class="entry-content">\n          {inner}\n        </div>'


def ask_card(text):
    return f'''<div class="ask-card" data-reveal>
            <h3>Masz pytanie?</h3>
            <p>{text}</p>
            <a href="{TEL}" class="btn btn--dark btn--block">{PHONE}</a>
            <a href="mailto:{MAIL}" class="ask-card__mail">{MAIL}</a>
          </div>'''


def service_card(r, o):
    return f'''          <article class="other" data-reveal>
            <div class="other__media"><img src="{r}{o["card_img"]}" alt="" loading="lazy"></div>
            <div class="other__body">
              <h3><a href="{r}{o["slug"]}/">{e(o["name"])}</a></h3>
              <p>{o["short"]}</p>
              <span class="arrow-link">Dowiedz się więcej <span class="arrow">→</span></span>
            </div>
          </article>'''


# -------------------------------------------------------------- services ----

def service_page(s):
    r = '../'
    name = e(s['name'])
    img = f'{r}assets/img/uslugi/{s["img"]}'
    trail = [('Strona główna', r), ('Usługi', f'{r}#uslugi'), (s['name'], None)]
    ld = [{'@context': 'https://schema.org', '@type': 'Service', 'name': s['name'], 'serviceType': s['name'],
           'description': s['desc'], 'areaServed': ['Wrocław', 'Dolny Śląsk'], 'provider': BUSINESS},
          breadcrumb_ld(trail)]

    highlights = '\n'.join(f'''        <div class="trust__card" data-reveal>
          <div class="hl__icon">{icon(ic)}</div>
          <div class="trust__title">{t}</div>
          <div class="trust__txt">{d}</div>
        </div>''' for ic, t, d in s['highlights'])
    steps = '\n'.join(f'''          <li class="step">
            <div class="step__rail"><span class="step__line"></span>
              <span class="step__dot">
                <svg viewBox="0 0 24 24" class="step__icon">{ICONS[ic]}</svg>
                <span class="step__num-mob">{i + 1:02d}</span>
              </span><span class="step__line"></span></div>
            <div class="step__body">
              <div class="step__num">{i + 1:02d}</div>
              <h3>{t}</h3>
              <p>{d}</p>
            </div>
          </li>''' for i, (ic, t, d) in enumerate(s['steps']))
    gallery = '\n'.join(
        f'          <button type="button" class="gallery__item" data-reveal data-full="{img}-{n}.jpg"><img src="{img}-{n}.jpg" alt="{e(alt)}" loading="lazy"></button>'
        for n, alt in zip((1, 2, 3), s['gallery_alt']))
    svc_nav = '\n'.join(
        '          <a href="{}{}/"{}>{} <span class="arrow">→</span></a>'.format(
            r, o['slug'], ' aria-current="page"' if o is s else '', e(o['name']))
        for o in SERVICES)
    others = '\n'.join(service_card(r, o) for o in SERVICES if o is not s)

    return head(r, s['title'], s['desc'], f'{img}-hero.jpg', ld, preload=f'{img}-hero.jpg') + header(r, 'uslugi') + f'''
  <main id="main">
    <section class="hero hero--service" id="top">
      <img class="hero__bg" src="{img}-hero.jpg" alt="" fetchpriority="high">
      <div class="hero__shade" aria-hidden="true"></div>
      <div class="container hero__grid">
        <div class="hero__copy">
          {crumbs(trail)}
          <div class="pill" data-anim="1">{s["pill"]}</div>
          <h1 class="hero__title" data-anim="2">{s["h1"]}</h1>
          <p class="hero__lead" data-anim="3">{s["lead"]}</p>
          <div class="hero__actions" data-anim="4">
            <a href="#kontakt" class="btn btn--primary btn--lg btn--glow">Poproś o wycenę</a>
            <a href="{TEL}" class="btn btn--ghost-light btn--lg">Zadzwoń: {PHONE}</a>
          </div>{PROOF}
        </div>
{hero_form(name, s["chip"], f"{name} — zostaw dane kontaktowe, oddzwonimy.")}
      </div>
    </section>

    <section class="trust" aria-label="Najważniejsze informacje">
      <div class="container trust__grid trust__grid--hl">
{highlights}
      </div>
    </section>

    <section class="section" id="opis">
      <div class="container svc">
        <article class="svc__main">
        {entry_content(s["intro"], s["sections"])}
        </article>
        <aside class="svc__aside">
          {ask_card(f'Zadzwoń i zapytaj o {s["name"].lower()} — doradzimy i przygotujemy wycenę.')}
          <nav class="svc-nav" aria-label="Usługi" data-reveal>
            <span class="svc-nav__title">USŁUGI</span>
{svc_nav}
          </nav>
        </aside>
      </div>
    </section>

    <section class="section section--dark" id="proces">
      <div class="container">
        <div class="section-head section-head--narrow" data-reveal>
          <div class="section-head__text">
            <span class="eyebrow eyebrow--light">JAK PRACUJEMY</span>
            <h2 class="h2">{s["steps_title"]}</h2>
            <p class="lead lead--light">{s["steps_lead"]}</p>
          </div>
        </div>
        <ol class="steps" data-steps>
{steps}
        </ol>
        <div class="btn-row process__actions" data-reveal>
          <a href="#kontakt" class="btn btn--primary btn--md btn--glow">Poproś o wycenę</a>
          <a href="{TEL}" class="btn btn--ghost-light btn--md only-desk">{PHONE}</a>
        </div>
      </div>
    </section>

    <section class="section" id="realizacje">
      <div class="container">
        <div class="section-head section-head--gallery" data-reveal>
          <div class="section-head__text">
            <span class="eyebrow">REALIZACJE</span>
            <h2 class="h2">Nasze realizacje</h2>
            <p class="lead">Ważne są zarówno prawidłowe działanie instalacji, jak i estetyka wykonania.</p>
          </div>
          <a href="{r}#realizacje" class="arrow-link only-desk">Zobacz więcej realizacji <span class="arrow">→</span></a>
        </div>
        <div class="gallery gallery--3">
{gallery}
        </div>
      </div>
    </section>

    <section class="section section--tint section--bt" id="inne-uslugi">
      <div class="container">
        <div class="section-head" data-reveal>
          <div class="section-head__text">
            <span class="eyebrow">USŁUGI</span>
            <h2 class="h2">Zobacz także</h2>
            <p class="lead">Pozostałe usługi Klimat OK we Wrocławiu i okolicach.</p>
          </div>
        </div>
        <div class="others">
{others}
        </div>
      </div>
    </section>
{contact(r, name, s["chip"], f"{s['name']}: czego potrzebujesz?")}
  </main>
''' + footer(r, 'uslugi')


# ------------------------------------------------------------------ blog ----

def post_meta(p, light=False):
    cls = 'post-meta post-meta--light' if light else 'post-meta'
    return (f'<div class="{cls}"><span class="post-meta__cat">{e(p["category"])}</span>'
            f'<time datetime="{p["date"]}">{p["date_pl"]}</time><span>{p["read"]}</span></div>')


def blog_index():
    r = '../'
    trail = [('Strona główna', r), ('Blog', None)]
    ld = [{'@context': 'https://schema.org', '@type': 'Blog', 'name': 'Blog Klimat OK', 'publisher': BUSINESS,
           'blogPost': [{'@type': 'BlogPosting', 'headline': p['title'], 'datePublished': p['date'],
                         'url': f'{p["slug"]}/'} for p in POSTS]},
          breadcrumb_ld(trail)]

    featured = POSTS[0]
    rest = POSTS[1:]
    feature = f'''        <article class="post-feature" data-reveal>
          <div class="post-feature__media"><img src="{r}{featured["cover"]}" alt="{e(featured["cover_alt"])}" loading="lazy"></div>
          <div class="post-feature__body">
            <span class="post-badge">Najnowszy wpis</span>
            {post_meta(featured)}
            <h2><a href="{featured["slug"]}/">{e(featured["title"])}</a></h2>
            <p>{featured["excerpt"]}</p>
            <span class="arrow-link">Czytaj artykuł <span class="arrow">→</span></span>
          </div>
        </article>'''
    cards = '\n'.join(f'''          <article class="post-card" data-reveal>
            <div class="post-card__media"><img src="{r}{p["cover"]}" alt="" loading="lazy"></div>
            <div class="post-card__body">
              {post_meta(p)}
              <h3><a href="{p["slug"]}/">{e(p["title"])}</a></h3>
              <span class="arrow-link">Czytaj <span class="arrow">→</span></span>
            </div>
          </article>''' for p in rest)
    soon = '\n'.join(f'''          <article class="post-card post-card--soon" data-reveal aria-label="Artykuł w przygotowaniu">
            <div class="post-card__media"><span class="soon-flake">{icon("doc")}</span></div>
            <div class="post-card__body">
              <div class="post-meta"><span class="post-meta__cat">{e(cat)}</span><span class="soon-tag"><i></i>Wkrótce</span></div>
              <h3>{e(title)}</h3>
              <div class="skeleton"><span></span><span></span></div>
            </div>
          </article>''' for cat, title in UPCOMING)

    return head(r, 'Blog — porady o klimatyzacji | Klimat OK',
                'Blog Klimat OK: porady o montażu i serwisie klimatyzacji, pompach ciepła i rekuperacji. Nowe artykuły już wkrótce.',
                f'{r}{featured["cover"]}', ld) + header(r, 'blog') + f'''
  <main id="main">
    <section class="hero hero--service hero--compact" id="top">
      <img class="hero__bg" src="{r}assets/img/hero.jpg" alt="" fetchpriority="high">
      <div class="hero__shade" aria-hidden="true"></div>
      <div class="container hero__grid">
        <div class="hero__copy">
          {crumbs(trail)}
          <div class="pill pill--live" data-anim="1"><i aria-hidden="true"></i>Nowe artykuły już wkrótce</div>
          <h1 class="hero__title" data-anim="2">Blog Klimat OK</h1>
          <p class="hero__lead" data-anim="3">Porady o klimatyzacji, pompach ciepła i rekuperacji — prosto od instalatorów. Przenosimy bloga na nową stronę: pierwszy artykuł już jest, kolejne pojawią się tu wkrótce.</p>
        </div>
      </div>
    </section>

    <section class="section section--tint" id="wpisy">
      <div class="container">
{feature}
{('        <div class="posts">' + chr(10) + cards + chr(10) + '        </div>') if rest else ''}
        <div class="section-head section-head--soon" data-reveal>
          <div class="section-head__text">
            <span class="eyebrow">W PRZYGOTOWANIU</span>
            <h2 class="h2 h2--sm">Wkrótce na blogu</h2>
          </div>
        </div>
        <div class="posts">
{soon}
        </div>
      </div>
    </section>

    <section class="section" id="uslugi-blog">
      <div class="container">
        <div class="section-head" data-reveal>
          <div class="section-head__text">
            <span class="eyebrow">USŁUGI</span>
            <h2 class="h2">Potrzebujesz pomocy fachowca?</h2>
            <p class="lead">Zamiast czytać — zadzwoń. Doradzimy, dobierzemy i zamontujemy.</p>
          </div>
        </div>
        <div class="others others--4">
{chr(10).join(service_card(r, o) for o in SERVICES)}
        </div>
      </div>
    </section>
{contact(r)}
  </main>
''' + footer(r, 'blog')


def post_page(p):
    r = '../../'
    trail = [('Strona główna', r), ('Blog', f'{r}blog/'), (p['title'], None)]
    svc = next(s for s in SERVICES if s['slug'] == p['service'])
    ld = [{'@context': 'https://schema.org', '@type': 'BlogPosting', 'headline': p['title'], 'description': p['desc'],
           'datePublished': p['date'], 'image': f'{r}{p["cover"]}', 'author': {'@type': 'Organization', 'name': 'Klimat OK'},
           'publisher': BUSINESS},
          {'@context': 'https://schema.org', '@type': 'FAQPage', 'mainEntity': [
              {'@type': 'Question', 'name': q, 'acceptedAnswer': {'@type': 'Answer', 'text': a}} for q, a in p['faq']]},
          breadcrumb_ld(trail)]

    faq = '\n'.join(
        f'<details class="wp-block-details"{" open" if i == 0 else ""}><summary>{e(q)}</summary><p>{e(a)}</p></details>'
        for i, (q, a) in enumerate(p['faq']))
    extra = (f'<div class="wp-block-group callout"><p>W skrócie</p><p>{p["summary"]}</p></div>\n'
             f'<h2>Najczęstsze pytania</h2>\n{faq}')

    return head(r, p['seo_title'], p['desc'], f'{r}{p["cover"]}', ld) + header(r, 'blog') + f'''
  <main id="main">
    <section class="hero hero--service hero--article" id="top">
      <img class="hero__bg" src="{r}{p["cover"]}" alt="" fetchpriority="high">
      <div class="hero__shade" aria-hidden="true"></div>
      <div class="container hero__grid">
        <div class="hero__copy">
          {crumbs(trail)}
          <div data-anim="1">{post_meta(p, light=True)}</div>
          <h1 class="hero__title" data-anim="2">{e(p["title"])}</h1>
          <p class="hero__lead" data-anim="3">{p["excerpt"]}</p>
        </div>
      </div>
    </section>

    <div class="container article-cover" data-reveal>
      <img src="{r}{p["cover"]}" alt="{e(p["cover_alt"])}">
    </div>

    <section class="section section--article" id="artykul">
      <div class="container svc">
        <article class="svc__main">
        {entry_content(p["intro"], p["sections"], extra)}

          <div class="article-end" data-reveal>
            <a href="{r}blog/" class="arrow-link arrow-link--back"><span class="arrow">←</span> Wszystkie wpisy</a>
            <div class="share">
              <span>Udostępnij:</span>
              <button type="button" class="share__btn" data-share>Kopiuj link</button>
            </div>
          </div>
        </article>
        <aside class="svc__aside">
          <nav class="toc" aria-label="Spis treści" data-toc data-reveal>
            <span class="svc-nav__title">SPIS TREŚCI</span>
          </nav>
          <div class="related" data-reveal>
            <span class="svc-nav__title">POWIĄZANA USŁUGA</span>
{service_card(r, svc)}
          </div>
        </aside>
      </div>
    </section>
{contact(r, e(svc["name"]), 3, 'Serwis, przegląd, awaria…')}
  </main>
''' + footer(r, 'blog')


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')
    print('wrote', path.relative_to(ROOT.parent))


def main():
    for s in SERVICES:
        write(ROOT / s['slug'] / 'index.html', service_page(s))
    write(ROOT / 'blog' / 'index.html', blog_index())
    for p in POSTS:
        write(ROOT / 'blog' / p['slug'] / 'index.html', post_page(p))


if __name__ == '__main__':
    main()
