#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generates every static page of the GETMON site.

  getmon/<service-slug>/index.html   <- content_services.py
  getmon/blog/index.html             <- content_blog.py
  getmon/blog/<post-slug>/index.html <- content_blog.py
  getmon/polityka-prywatnosci/index.html

The home page (getmon/index.html) is hand-written, but it uses the SAME chrome
helpers from this file, so header/footer/drawer/dock change in one place:
run this script and it rewrites the chrome inside index.html too.

Run:  python3 getmon/_build/build_pages.py
"""
import html
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from content_services import SERVICES, NAV_GROUPS, SHORT  # noqa: E402
from content_blog import POSTS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PHONE = '884 884 823'
PHONE2 = '+48 517 211 442'
TEL = 'tel:+48884884823'
TEL2 = 'tel:+48517211442'
MAIL = 'biuro@getmon.pl'
ADDRESS = 'Centralna 37/U, 52-114 Wrocław'
REVIEWS_URL = 'https://share.google/Vi7KtLl2xMIycERBV'
CHIPS = ['Klimatyzacja', 'Wentylacja', 'Pompa ciepła', 'Monitoring', 'Alarm']
BUSINESS = {
    '@context': 'https://schema.org', '@type': 'HVACBusiness', 'name': 'GETMON',
    'telephone': '+48884884823', 'email': MAIL,
    'address': {'@type': 'PostalAddress', 'streetAddress': 'Centralna 37/U',
                'postalCode': '52-114', 'addressLocality': 'Wrocław', 'addressCountry': 'PL'},
    'areaServed': ['Wrocław', 'Dolny Śląsk'],
    'aggregateRating': {'@type': 'AggregateRating', 'ratingValue': '4.9', 'reviewCount': '257'},
}
e = html.escape


# ================================================================== chrome ==

def head(r, title, desc, og_img, ld, preload=None):
    pre = f'\n  <link rel="preload" as="image" href="{preload}">' if preload else ''
    return f'''<!doctype html>
<!-- Generated by _build/build_pages.py — edit the content files there, not this file. -->
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>{e(title)}</title>
  <meta name="description" content="{e(desc)}">
  <meta name="theme-color" content="#0A1A20">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="pl_PL">
  <meta property="og:title" content="{e(title)}">
  <meta property="og:description" content="{e(desc)}">
  <meta property="og:image" content="{og_img}">
  <link rel="icon" href="{r}assets/img/cropped-getmon_fav-192x192.png" type="image/png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@500;600;700;800&family=IBM+Plex+Sans:wght@400;500;600&display=swap" rel="stylesheet">{pre}
  <link rel="stylesheet" href="{r}css/styles.css">
  <script>document.documentElement.classList.add('js');</script>
  <script type="application/ld+json">
{json.dumps(ld, ensure_ascii=False, indent=2)}
  </script>
</head>
<body data-form-endpoint="">
  <a class="skip-link" href="#main">Przejdź do treści</a>
'''


CARET = ('<svg class="nav__caret" viewBox="0 0 10 6" fill="none" stroke="currentColor" '
         'stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
         '<path d="M1 1.5 5 5 9 1.5"></path></svg>')


def topbar():
    return f'''
  <div class="topbar">
    <div class="container topbar__inner">
      <span>Klimatyzacja · wentylacja · pompy ciepła · monitoring · alarmy</span>
      <a href="mailto:{MAIL}" class="topbar__mail">{MAIL}</a>
      <a href="{TEL}" class="topbar__tel">{PHONE}</a>
    </div>
  </div>
'''


def header(r, active_group=None, active_slug=None):
    """active_group: nav group key, or 'blog'. active_slug: current service slug."""
    items = []
    for key, label, hub, children in NAV_GROUPS:
        on = ' is-active' if key == active_group else ''
        if not children:
            items.append(f'        <a href="{r}{hub}/" class="nav__link{on}">{label}</a>')
            continue
        links = '\n'.join(
            '          <a href="%s%s/"%s>%s</a>'
            % (r, c, ' class="is-active"' if c == active_slug else '', SHORT[c])
            for c in children)
        items.append(f'''        <div class="nav__item">
          <a href="{r}{hub}/" class="nav__link{on}">{label}{CARET}</a>
          <div class="nav__menu">
{links}
          </div>
        </div>''')
    items.append(f'        <a href="{r}blog/" class="nav__link'
                 f'{" is-active" if active_group == "blog" else ""}">Blog</a>')
    nav = '\n'.join(items)
    return f'''
  <header class="header" id="header">
    <div class="container header__inner">
      <a href="{r}" class="header__logo" aria-label="GETMON — strona główna">
        <img src="{r}assets/img/logo.svg" alt="GETMON" width="120" height="26">
      </a>
      <nav class="nav" aria-label="Główna nawigacja">
{nav}
      </nav>
      <a href="#kontakt" class="btn btn--primary btn--sm header__cta">Darmowa wycena</a>
      <a href="{TEL}" class="header__phone">{PHONE}</a>
      <button class="burger" type="button" aria-label="Menu" aria-expanded="false" aria-controls="drawer">
        <span></span><span></span><span></span>
      </button>
    </div>
  </header>
'''


def chips(active_label=None):
    out = []
    for i, c in enumerate(CHIPS):
        on = (c == active_label) if active_label else (i == 0)
        out.append(f'<button type="button" class="chip{" is-active" if on else ""}" role="radio" '
                   f'aria-checked="{"true" if on else "false"}">{c}</button>')
    return '\n                    '.join(out)


def lead_form(fid, service='', chip=None, full=False, r=''):
    """THE lead form. Same markup in the hero and in #kontakt — only `full`
    adds e-mail + message + consent, so the two never drift apart."""
    extra = ''
    if full:
        extra = f'''
              <div class="form-row">
                <div class="field">
                  <label for="{fid}-mail" class="field-label">E-mail (opcjonalnie)</label>
                  <input id="{fid}-mail" name="email" type="email" placeholder="jan@example.pl" autocomplete="email">
                </div>
                <div class="field">
                  <label for="{fid}-msg" class="field-label">Wiadomość (opcjonalnie)</label>
                  <input id="{fid}-msg" name="wiadomosc" placeholder="Krótko o obiekcie i zakresie prac">
                </div>
              </div>'''
    srv = f' data-service="{e(service)}"' if service else ''
    return f'''
            <form class="lead-form" data-form="{fid}"{srv} novalidate>
              <fieldset class="chips-field">
                <legend class="field-label">Czego dotyczy zapytanie?</legend>
                <div class="chips" role="radiogroup">
                    {chips(chip)}
                </div>
              </fieldset>
              <div class="form-row">
                <div class="field">
                  <label for="{fid}-imie" class="field-label">Nazwa / imię</label>
                  <input id="{fid}-imie" name="imie" placeholder="Jan" autocomplete="name" required>
                  <span class="field-error">Podaj imię lub nazwę</span>
                </div>
                <div class="field">
                  <label for="{fid}-tel" class="field-label">Telefon</label>
                  <input id="{fid}-tel" name="telefon" type="tel" placeholder="500 100 200" autocomplete="tel" required>
                  <span class="field-error">Podaj numer telefonu</span>
                </div>
              </div>{extra}
              <button type="submit" class="btn btn--primary btn--block btn--submit">
                <span class="btn__spin" aria-hidden="true"></span>Umów darmową wycenę
              </button>
              <p class="form-note">Wysyłając formularz, akceptujesz <a href="{r}polityka-prywatnosci/">Politykę Prywatności</a>.</p>
            </form>
            <div class="form-success" hidden>
              <div class="form-success__icon" aria-hidden="true">
                <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#0E7C8C" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12.5l5 5L20 6.5"></path></svg>
              </div>
              <h3>Dziękujemy. Zapytanie zostało wysłane.</h3>
              <p>Skontaktujemy się w sprawie zgłoszenia.</p>
            </div>'''


def quote_card(fid, service='', chip=None, full=False, r='', flat=False, note=None):
    note = note or 'Zostaw kontakt i napisz, czego potrzebujesz.'
    cls = 'quote-card quote-card--flat' if flat else 'quote-card'
    return f'''
        <div class="{cls}" data-anim style="--a:6">
          <div class="quote-card__head">
            <h2>Darmowa wycena</h2>
            <p>{e(note)}</p>
          </div>
          <div class="quote-card__body">{lead_form(fid, service, chip, full, r)}
          </div>
        </div>'''


def band(r, title, txt):
    return f'''
    <section class="band">
      <img class="band__bg" src="{r}assets/img/bg/band.jpg" alt="" loading="lazy" width="1800" height="1200">
      <div class="band__shade" aria-hidden="true"></div>
      <div class="container band__inner" data-reveal>
        <div>
          <h2 class="band__title">{e(title)}</h2>
          <p class="band__txt">{e(txt)}</p>
        </div>
        <div class="btn-row">
          <a href="{TEL}" class="btn btn--white btn--band">Zadzwoń: {PHONE}</a>
          <a href="#kontakt" class="btn btn--ghost-light btn--band">Darmowa wycena</a>
        </div>
      </div>
    </section>
'''


def contact(r, service='', chip=None):
    return f'''
    <section class="contact" id="kontakt">
      <img class="contact__bg" src="{r}assets/img/bg/kontakt.jpg" alt="" loading="lazy" width="1800" height="1200">
      <div class="contact__shade" aria-hidden="true"></div>
      <div class="container contact__grid">
        <div class="contact__copy" data-reveal>
          <h2>Opowiedz nam,<br class="br-desk"> czego potrzebujesz</h2>
          <p class="contact__lead">Skontaktuj się z GETMON i umów darmową wycenę.</p>
          <a href="{TEL}" class="contact__big">{PHONE}</a>
          <div class="contact__meta">
            <a href="{TEL2}">{PHONE2}</a>
            <a href="mailto:{MAIL}">{MAIL}</a>
            <span>{ADDRESS}</span>
          </div>
        </div>
        <div data-reveal>{quote_card('kontakt', service, chip, full=True, r=r, flat=True,
                                     note='Odpowiemy tak szybko, jak to możliwe.')}
        </div>
      </div>
    </section>
'''


def footer(r):
    def col(title, links):
        ls = '\n'.join(f'        <a href="{h}">{t}</a>' for t, h in links)
        return f'''      <div class="footer__col">
        <span class="footer__head">{title}</span>
{ls}
      </div>'''

    uslugi = [(SHORT[s], f'{r}{s}/') for s in
              ['klimatyzacja-wroclaw', 'wentylacja-wroclaw', 'pompy-ciepla-wroclaw',
               'montaz-monitoringu-wroclaw', 'systemy-alarmowe-wroclaw']]
    uslugi[0] = ('Klimatyzacja', uslugi[0][1])
    uslugi[3] = ('Monitoring', uslugi[3][1])
    uslugi[4] = ('Systemy alarmowe', uslugi[4][1])
    klima = [(SHORT[s], f'{r}{s}/') for s in NAV_GROUPS[0][3][1:]]
    return f'''
  <footer class="footer">
    <div class="container footer__grid">
      <div>
        <img class="footer__logo" src="{r}assets/img/logo.svg" alt="GETMON" width="138" height="30">
        <p>Nowoczesne systemy, niezawodny komfort. Instalacje dla domu i firmy we Wrocławiu.</p>
      </div>
{col('Kontakt', [('+48 ' + PHONE, TEL), (PHONE2, TEL2), (MAIL, 'mailto:' + MAIL)])}
{col('Usługi', uslugi)}
{col('Klimatyzacja', klima)}
{col('Firma', [('Blog', f'{r}blog/'), ('Opinie', REVIEWS_URL),
               ('Polityka prywatności', f'{r}polityka-prywatnosci/')])}
    </div>
    <div class="container footer__bottom">
      <span>© <span data-year>2026</span> GETMON · {ADDRESS}</span>
      <span>NIP i dane rejestrowe — <a href="mailto:{MAIL}">zapytaj w biurze</a></span>
    </div>
  </footer>

  <div class="dock" aria-hidden="true">
    <div class="dock__card">
      <a href="{TEL}" class="btn btn--dark btn--dock" tabindex="-1">Zadzwoń</a>
      <a href="#kontakt" class="btn btn--primary btn--dock btn--pulse" tabindex="-1">Darmowa wycena</a>
    </div>
  </div>

  <div class="mbar">
    <a href="{TEL}" class="btn btn--dark">Zadzwoń</a>
    <a href="#kontakt" class="btn btn--primary btn--pulse">Darmowa wycena</a>
  </div>

  <div class="drawer" id="drawer" aria-hidden="true" aria-label="Menu">
    <div class="drawer__scrim" data-close></div>
    <div class="drawer__panel" role="dialog" aria-modal="true" aria-label="Menu">
      <div class="drawer__top">
        <a href="{r}" class="header__logo" data-close aria-label="GETMON — strona główna">
          <img src="{r}assets/img/logo.svg" alt="GETMON" width="120" height="26">
        </a>
        <button class="drawer__close" type="button" aria-label="Zamknij menu" data-close>✕</button>
      </div>
      <nav class="drawer__nav">
{drawer_nav(r)}
      </nav>
      <div class="drawer__actions">
        <a href="#kontakt" class="btn btn--primary" data-close>Umów darmową wycenę</a>
        <a href="{TEL}" class="btn btn--ghost" data-close>{PHONE}</a>
      </div>
    </div>
  </div>

  <div class="lightbox" hidden>
    <button class="lightbox__close" type="button" aria-label="Zamknij">✕</button>
    <img src="" alt="">
  </div>

  <script src="{r}js/main.js" defer></script>
</body>
</html>
'''


def drawer_nav(r):
    out = []
    for key, label, hub, children in NAV_GROUPS:
        if not children:
            out.append(f'        <a href="{r}{hub}/" data-close>{label}</a>')
            continue
        out.append(f'        <span class="drawer__group">{label}</span>')
        for c in children:
            out.append(f'        <a href="{r}{c}/" class="is-sub" data-close>{SHORT[c]}</a>')
    out.append(f'        <a href="{r}blog/" data-close>Blog</a>')
    out.append('        <a href="#kontakt" data-close>Kontakt</a>')
    return '\n'.join(out)


# =================================================================== blocks ==

def render_blocks(blocks, r):
    out = []
    for b in blocks:
        if 'callout' in b:
            title, body = b['callout']
            out.append(f'        <div class="callout" data-reveal><p>{e(title)}</p><p>{e(body)}</p></div>')
            continue
        if b.get('h2'):
            out.append(f'        <h2 data-reveal>{e(b["h2"])}</h2>')
        for p in b.get('p', []):
            out.append(f'        <p data-reveal>{e(p)}</p>')
        if b.get('ul'):
            lis = '\n'.join(f'          <li>{e(x)}</li>' for x in b['ul'])
            out.append(f'        <ul data-reveal>\n{lis}\n        </ul>')
        for h3, ps in b.get('h3', []):
            out.append(f'        <h3 data-reveal>{e(h3)}</h3>')
            for p in ps:
                out.append(f'        <p data-reveal>{e(p)}</p>')
        if b.get('img'):
            cap = f'\n          <figcaption>{e(b["cap"])}</figcaption>' if b.get('cap') else ''
            out.append(f'''        <figure data-reveal>
          <img src="{r}assets/img/bg/{b["img"]}.jpg" alt="{e(b.get("cap", ""))}" loading="lazy" width="1800" height="1200">{cap}
        </figure>''')
    return '\n'.join(out)


def page_hero(r, d, crumbs):
    ticks = ''
    if d.get('ticks'):
        rows = '\n'.join(f'            <div class="tick">{e(t)}</div>' for t in d['ticks'])
        ticks = f'\n          <div class="ticks" data-anim style="--a:5">\n{rows}\n          </div>'
    cr = '\n'.join(crumbs)
    return f'''
    <section class="hero hero--page" id="top">
      <img class="hero__bg" src="{r}assets/img/bg/{d["bg"]}.jpg" alt="" width="1800" height="1200" fetchpriority="high">
      <div class="hero__shade" aria-hidden="true"></div>
      <div class="container hero__grid">
        <div class="hero__copy">
          <nav class="crumbs" aria-label="Okruszki" data-anim style="--a:1">
{cr}
          </nav>
          <div class="pill" data-anim style="--a:2">{e(d["eyebrow"])} · WROCŁAW</div>
          <h1 class="hero__title" data-anim style="--a:3">{e(d["h1"])}</h1>
          <p class="hero__lead" data-anim style="--a:4">{e(d["lead"])}</p>{ticks}
          <div class="hero__actions" data-anim style="--a:6">
            <a href="#kontakt" class="btn btn--primary btn--lg">Umów darmową wycenę</a>
            <a href="{TEL}" class="btn btn--ghost-light btn--lg">Zadzwoń: {PHONE}</a>
          </div>
        </div>
{quote_card('hero', d["nav"], d.get("chip"), r=r)}
      </div>
    </section>
'''


def proof(r):
    """Why-us block. Every claim is checked: the rating comes from the Google
    listing getmon.pl itself links to, the rest from getmon.pl's own copy."""
    cards = [
        ('4,9 / 257 opinii', 'Ocena w Google od klientów z Wrocławia i okolic'),
        ('Darmowa wycena', 'Koszt i zakres prac poznajesz przed startem'),
        ('Certyfikaty i uprawnienia', 'Montaż zgodny z wymaganiami producentów'),
        ('Serwis po montażu', 'Przeglądy i obsługa instalacji, nie tylko montaż'),
    ]
    items = '\n'.join(
        '        <div class="trust__card" data-reveal>\n'
        '          <div class="trust__title">%s</div>\n'
        '          <div class="trust__txt">%s</div>\n'
        '        </div>' % (e(t), e(x)) for t, x in cards)
    return '''
    <section class="section section--tint section--bt">
      <div class="container">
        <div class="section-head" data-reveal>
          <span class="eyebrow">DLACZEGO GETMON</span>
          <h2 class="h2 h2--sm">Cztery powody, dla których klienci zostają</h2>
        </div>
        <div class="trust__grid">
%s
        </div>
      </div>
    </section>
''' % items


def related(r, slugs):
    cards = '\n'.join(
        f'''        <a class="rel-card" href="{r}{s}/">
          <strong>{SHORT[s]}</strong>
          <span>{e(SERVICES[s]["eyebrow"].capitalize())}</span>
        </a>''' for s in slugs)
    return f'''
    <section class="section section--tint section--bt">
      <div class="container">
        <div class="section-head" data-reveal>
          <span class="eyebrow">SPRAWDŹ RÓWNIEŻ</span>
          <h2 class="h2 h2--sm">Powiązane usługi</h2>
        </div>
        <div class="rel-grid" data-reveal>
{cards}
        </div>
      </div>
    </section>
'''


# ==================================================================== pages ==

def build_service(slug, d):
    r = '../'
    ld = dict(BUSINESS)
    ld = {'@context': 'https://schema.org', '@graph': [BUSINESS, {
        '@type': 'Service', 'name': d['h1'], 'description': d['desc'],
        'provider': {'@type': 'HVACBusiness', 'name': 'GETMON'}, 'areaServed': 'Wrocław'}]}
    crumbs = [f'            <a href="{r}">Strona główna</a>', '            <span>/</span>',
              f'            <span>{e(d["nav"])}</span>']
    out = [head(r, d['title'], d['desc'], f'{r}assets/img/bg/{d["bg"]}.jpg', ld,
                preload=f'{r}assets/img/bg/{d["bg"]}.jpg'),
           topbar(), header(r, d['group'], slug),
           '\n  <main id="main">',
           page_hero(r, d, crumbs),
           f'''
    <section class="section">
      <div class="container article-layout">
        <div class="prose">
{render_blocks(d["blocks"], r)}
        </div>
        <aside class="article-aside">
          <nav class="toc" data-toc aria-label="Spis treści">
            <span class="toc__head">Na tej stronie</span>
          </nav>
          <div class="faq__card">
            <h3>Masz pytanie?</h3>
            <p>Zadzwoń do biura GETMON i zapytaj o zakres prac.</p>
            <a href="{TEL}" class="btn btn--dark btn--block">{PHONE}</a>
          </div>
        </aside>
      </div>
    </section>
''',
           proof(r),
           related(r, d['related']),
           band(r, 'Darmowa wycena, zero zobowiązań',
                'Opisz obiekt i zakres prac — odezwiemy się z konkretną propozycją.'),
           contact(r, d['nav'], d.get('chip')),
           '  </main>', footer(r)]
    write(ROOT / slug / 'index.html', ''.join(out))


def build_blog_index():
    r = '../'
    first, rest = POSTS[0], POSTS[1:]
    cards = '\n'.join(f'''        <a class="post-card" href="{r}blog/{p["slug"]}/">
          <div class="post-card__media"><img src="{r}assets/img/bg/{p["img"]}.jpg" alt="" loading="lazy" width="1800" height="1200"></div>
          <div class="post-card__body">
            <div class="post-card__meta"><span class="tag">{e(p["cat"])}</span><span>{p["date_pl"]}</span></div>
            <h3>{e(p["title"])}</h3>
            <p>{e(p["lead"])}</p>
          </div>
        </a>''' for p in rest)
    ld = {'@context': 'https://schema.org', '@type': 'Blog', 'name': 'Blog GETMON',
          'blogPost': [{'@type': 'BlogPosting', 'headline': p['title'],
                        'datePublished': p['date'],
                        'url': f'https://getmon.pl/blog/{p["slug"]}/'} for p in POSTS]}
    out = [head(r, 'Blog — klimatyzacja, wentylacja i bezpieczeństwo | GETMON',
                'Artykuły GETMON o klimatyzacji, rekuperacji, pompach ciepła i systemach '
                'bezpieczeństwa. Ceny, porady i nasze realizacje z Wrocławia.',
                f'{r}assets/img/bg/blog.jpg', ld),
           topbar(), header(r, 'blog'),
           '\n  <main id="main">',
           f'''
    <section class="hero hero--page" id="top">
      <img class="hero__bg" src="{r}assets/img/bg/blog.jpg" alt="" width="1800" height="1200" fetchpriority="high">
      <div class="hero__shade" aria-hidden="true"></div>
      <div class="container hero__grid">
        <div class="hero__copy">
          <nav class="crumbs" aria-label="Okruszki" data-anim style="--a:1">
            <a href="{r}">Strona główna</a>
            <span>/</span>
            <span>Blog</span>
          </nav>
          <div class="pill" data-anim style="--a:2">BLOG GETMON</div>
          <h1 class="hero__title" data-anim style="--a:3">Porady, ceny<br class="br-desk"> i nasze realizacje</h1>
          <p class="hero__lead" data-anim style="--a:4">Piszemy o tym, o co pytacie najczęściej: ile kosztuje instalacja, co wybrać do konkretnego obiektu i jak wygląda praca na miejscu.</p>
        </div>
{quote_card('hero', '', None, r=r)}
      </div>
    </section>

    <section class="section">
      <div class="container">
        <a class="post-feature" href="{r}blog/{first["slug"]}/" data-reveal>
          <div class="post-feature__media"><img src="{r}assets/img/bg/{first["img"]}.jpg" alt="" width="1800" height="1200"></div>
          <div class="post-feature__body">
            <div class="post-card__meta"><span class="tag">{e(first["cat"])}</span><span>{first["date_pl"]}</span></div>
            <h2>{e(first["title"])}</h2>
            <p>{e(first["lead"])}</p>
            <span class="arrow-link">Czytaj artykuł <span class="arrow">→</span></span>
          </div>
        </a>
        <div class="posts" data-reveal>
{cards}
        </div>
      </div>
    </section>
''',
           band(r, 'Wolisz zapytać wprost?', 'Zadzwoń — doradzimy bez zobowiązań i bez sprzedażowego nacisku.'),
           contact(r),
           '  </main>', footer(r)]
    write(ROOT / 'blog' / 'index.html', ''.join(out))


def build_post(p):
    r = '../../'
    svc = SERVICES[p['service']]
    others = [q for q in POSTS if q['slug'] != p['slug']]
    cards = '\n'.join(f'''        <a class="post-card" href="{r}blog/{q["slug"]}/">
          <div class="post-card__media"><img src="{r}assets/img/bg/{q["img"]}.jpg" alt="" loading="lazy" width="1800" height="1200"></div>
          <div class="post-card__body">
            <div class="post-card__meta"><span class="tag">{e(q["cat"])}</span><span>{q["date_pl"]}</span></div>
            <h3>{e(q["title"])}</h3>
            <p>{e(q["lead"])}</p>
          </div>
        </a>''' for q in others)
    ld = {'@context': 'https://schema.org', '@type': 'BlogPosting', 'headline': p['title'],
          'description': p['desc'], 'datePublished': p['date'],
          'image': f'https://getmon.pl/assets/img/bg/{p["img"]}.jpg',
          'author': {'@type': 'Organization', 'name': 'GETMON'},
          'publisher': {'@type': 'Organization', 'name': 'GETMON'}}
    out = [head(r, f'{p["title"]} | Blog GETMON', p['desc'],
                f'{r}assets/img/bg/{p["img"]}.jpg', ld,
                preload=f'{r}assets/img/bg/{p["img"]}.jpg'),
           topbar(), header(r, 'blog'),
           '\n  <main id="main">',
           f'''
    <section class="hero hero--page" id="top">
      <img class="hero__bg" src="{r}assets/img/bg/{p["img"]}.jpg" alt="" width="1800" height="1200" fetchpriority="high">
      <div class="hero__shade" aria-hidden="true"></div>
      <div class="container hero__grid">
        <div class="hero__copy">
          <nav class="crumbs" aria-label="Okruszki" data-anim style="--a:1">
            <a href="{r}">Strona główna</a>
            <span>/</span>
            <a href="{r}blog/">Blog</a>
          </nav>
          <h1 class="hero__title" data-anim style="--a:3">{e(p["title"])}</h1>
          <p class="hero__lead" data-anim style="--a:4">{e(p["lead"])}</p>
          <div class="post-meta" data-anim style="--a:5">
            <span class="tag">{e(p["cat"])}</span>
            <span>{p["date_pl"]}</span>
          </div>
        </div>
{quote_card('hero', svc["nav"], svc.get("chip"), r=r)}
      </div>
    </section>

    <section class="section">
      <div class="container article-layout">
        <div class="prose entry-content">
{render_blocks(p["blocks"], r)}
        </div>
        <aside class="article-aside">
          <nav class="toc" data-toc aria-label="Spis treści">
            <span class="toc__head">W tym artykule</span>
          </nav>
          <a class="rel-card" href="{r}{p["service"]}/">
            <strong>{SHORT[p["service"]]}</strong>
            <span>Powiązana usługa →</span>
          </a>
          <div class="faq__card">
            <h3>Masz pytanie?</h3>
            <p>Zadzwoń do biura GETMON i zapytaj o zakres prac.</p>
            <a href="{TEL}" class="btn btn--dark btn--block">{PHONE}</a>
          </div>
        </aside>
      </div>
    </section>

    <section class="section section--tint section--bt">
      <div class="container">
        <div class="section-head" data-reveal>
          <span class="eyebrow">CZYTAJ DALEJ</span>
          <h2 class="h2 h2--sm">Podobne artykuły</h2>
        </div>
        <div class="posts" data-reveal>
{cards}
        </div>
      </div>
    </section>
''',
           band(r, 'Od artykułu do realizacji', 'Opisz obiekt — przygotujemy darmową wycenę zakresu prac.'),
           contact(r, svc['nav'], svc.get('chip')),
           '  </main>', footer(r)]
    write(ROOT / 'blog' / p['slug'] / 'index.html', ''.join(out))


PRIVACY = [
    ('Administrator danych',
     ['Administratorem danych osobowych przekazanych w formularzu kontaktowym jest GETMON, '
      f'{ADDRESS}. Kontakt w sprawach dotyczących danych: {MAIL}, tel. {PHONE}.']),
    ('Zakres i cel przetwarzania',
     ['Formularz zbiera wyłącznie dane niezbędne do przygotowania wyceny i kontaktu zwrotnego: '
      'imię lub nazwę, numer telefonu oraz — opcjonalnie — adres e-mail i treść wiadomości. '
      'Dane przetwarzamy w celu odpowiedzi na zapytanie i przedstawienia oferty, na podstawie '
      'art. 6 ust. 1 lit. b oraz lit. f RODO (podjęcie działań na żądanie osoby, której dane '
      'dotyczą, oraz prawnie uzasadniony interes administratora).']),
    ('Okres przechowywania',
     ['Dane z zapytań ofertowych przechowujemy przez czas niezbędny do obsługi sprawy, a po jej '
      'zakończeniu przez okres przedawnienia ewentualnych roszczeń. Jeśli nie dojdzie do zawarcia '
      'umowy, dane usuwamy po zakończeniu korespondencji.']),
    ('Odbiorcy danych',
     ['Danych nie sprzedajemy ani nie udostępniamy podmiotom trzecim w celach marketingowych. '
      'Mogą być powierzone dostawcom usług hostingowych i pocztowych, wyłącznie w zakresie '
      'niezbędnym do obsługi korespondencji.']),
    ('Twoje prawa',
     ['Przysługuje Ci prawo dostępu do danych, ich sprostowania, usunięcia lub ograniczenia '
      'przetwarzania, prawo do przenoszenia danych oraz prawo wniesienia sprzeciwu wobec '
      'przetwarzania opartego na prawnie uzasadnionym interesie. Masz także prawo wniesienia '
      'skargi do Prezesa Urzędu Ochrony Danych Osobowych.']),
    ('Pliki cookies',
     ['Strona korzysta z plików cookies wyłącznie w zakresie niezbędnym do jej prawidłowego '
      'działania oraz — jeśli wyrazisz na to zgodę — do anonimowej statystyki odwiedzin. '
      'Ustawienia cookies możesz w każdej chwili zmienić w swojej przeglądarce.']),
]


def build_privacy():
    r = '../'
    blocks = [{'h2': t, 'p': ps} for t, ps in PRIVACY]
    ld = {'@context': 'https://schema.org', '@type': 'WebPage', 'name': 'Polityka prywatności'}
    out = [head(r, 'Polityka prywatności | GETMON',
                'Polityka prywatności serwisu GETMON — jakie dane zbieramy w formularzu wyceny, '
                'w jakim celu i jakie masz prawa.', f'{r}assets/img/bg/kontakt.jpg', ld),
           topbar(), header(r),
           '\n  <main id="main">',
           f'''
    <section class="hero hero--page" id="top">
      <img class="hero__bg" src="{r}assets/img/bg/kontakt.jpg" alt="" width="1800" height="1200">
      <div class="hero__shade" aria-hidden="true"></div>
      <div class="container hero__grid">
        <div class="hero__copy">
          <nav class="crumbs" aria-label="Okruszki" data-anim style="--a:1">
            <a href="{r}">Strona główna</a>
            <span>/</span>
            <span>Polityka prywatności</span>
          </nav>
          <h1 class="hero__title" data-anim style="--a:3">Polityka prywatności</h1>
          <p class="hero__lead" data-anim style="--a:4">Krótko i po ludzku: jakie dane zbieramy w formularzu wyceny, po co i co możesz z nimi zrobić.</p>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container">
        <div class="prose">
{render_blocks(blocks, r)}
        </div>
      </div>
    </section>
''',
           contact(r), '  </main>', footer(r)]
    write(ROOT / 'polityka-prywatnosci' / 'index.html', ''.join(out))


# ------------------------------------------------- chrome sync in index.html --

MARKS = [('TOPBAR', lambda: topbar()),
         ('HEROFORM', lambda: quote_card('hero', '', None, r='')),
         ('HEADER', lambda: header('', None, None)),
         ('BAND', lambda: band('', 'Darmowa wycena, zero zobowiązań',
                               'Opisz obiekt i zakres prac — odezwiemy się z konkretną propozycją.')),
         ('CONTACT', lambda: contact('')),
         ('FOOTER', lambda: footer(''))]


def sync_home():
    """index.html keeps <!--#X--> ... <!--/#X--> markers; refill them from here."""
    f = ROOT / 'index.html'
    if not f.exists():
        return
    s = f.read_text(encoding='utf-8')
    for name, fn in MARKS:
        pat = re.compile(f'(<!--#{name}-->)(.*?)(<!--/#{name}-->)', re.S)
        if not pat.search(s):
            print(f'  ! index.html: missing marker {name}')
            continue
        s = pat.sub(lambda m: m.group(1) + fn() + '  ' + m.group(3), s)
    # hero + in-page forms live in index.html itself; only chrome is synced.
    f.write_text(s, encoding='utf-8')
    print('  index.html (chrome synced)')


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')
    print(f'  {path.relative_to(ROOT)}')


def main():
    print('GETMON — building pages')
    for slug, d in SERVICES.items():
        build_service(slug, d)
    build_blog_index()
    for p in POSTS:
        build_post(p)
    build_privacy()
    sync_home()
    print(f'done: {len(SERVICES)} services + {len(POSTS)} posts + blog + privacy')


if __name__ == '__main__':
    main()
