#!/usr/bin/env python3
"""Generates the static sub-pages of the Dynamic AC site.

  dynamic-ac/<service-slug>/index.html   ← content_services.py
  dynamic-ac/kontakt/index.html          ← this file
  dynamic-ac/blog/index.html             ← content_blog.py
  dynamic-ac/blog/<post-slug>/index.html ← content_blog.py

The home page (dynamic-ac/index.html) is hand-written. Shared chrome (utility
bar, header, footer, floating CTAs, drawer) lives here, so change it in one
place and re-run.

Run:  python3 dynamic-ac/_build/build_pages.py
"""
import html
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from content_services import ICONS, SERVICES  # noqa: E402
from content_blog import POSTS, UPCOMING      # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SITE = 'https://wroclawklima.pl'
PHONE = '575 749 772'
TEL = 'tel:+48575749772'
ADDRESS = 'Wełniana 72, 54-061 Wrocław'
HOURS_WEEK = 'Pon–Pt 8:00–20:00'
HOURS_WEEKEND = 'Sb–Nd 9:00–17:00'
LEGAL = 'DYNAMIC AC ŁUKASZ KOWALSKI'
NIP = '6141613788'
REGON = '385242029'
REG_ADDRESS = 'ul. Słowiańska 17/2, 58-400 Kamienna Góra'

BUSINESS = {
    '@type': 'AutoRepair', 'name': 'Dynamic AC', 'legalName': LEGAL,
    'telephone': '+48575749772', 'taxID': NIP, 'vatID': 'PL' + NIP,
    'address': {'@type': 'PostalAddress', 'streetAddress': 'Wełniana 72', 'postalCode': '54-061',
                'addressLocality': 'Wrocław', 'addressCountry': 'PL'},
    'areaServed': {'@type': 'City', 'name': 'Wrocław'},
}

e = html.escape


def icon(name, size=26, cls='', stroke='1.7'):
    c = f' class="{cls}"' if cls else ''
    return (f'<svg{c} width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            f'stroke-width="{stroke}" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
            f'{ICONS[name]}</svg>')


# ---------------------------------------------------------------- chrome ----

def head(r, title, desc, og_img, ld, preload=None, canonical=''):
    pre = f'\n  <link rel="preload" as="image" href="{preload}">' if preload else ''
    can = f'\n  <link rel="canonical" href="{SITE}/{canonical}">' if canonical else ''
    blocks = '\n'.join(
        '  <script type="application/ld+json">\n' + json.dumps(x, ensure_ascii=False, indent=2) + '\n  </script>'
        for x in ld)
    return f'''<!doctype html>
<!-- Generated by _build/build_pages.py — edit the content files there, not this file. -->
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>{e(title)}</title>
  <meta name="description" content="{e(desc)}">
  <meta name="theme-color" content="#101A28">{can}
  <meta property="og:type" content="website">
  <meta property="og:locale" content="pl_PL">
  <meta property="og:site_name" content="Dynamic AC">
  <meta property="og:title" content="{e(title)}">
  <meta property="og:description" content="{e(desc)}">
  <meta property="og:image" content="{og_img}">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="icon" href="{r}assets/img/favicon.svg" type="image/svg+xml">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700;800&family=IBM+Plex+Sans:wght@400;500;600&display=swap" rel="stylesheet">{pre}
  <link rel="stylesheet" href="{r}css/styles.css">
  <script>document.documentElement.classList.add('js');</script>
{blocks}
</head>

<body data-form-endpoint="">
<a class="skip-link" href="#main">Przejdź do treści</a>
'''


def topbar():
    return f'''
<div class="topbar">
  <div class="container">
    <div class="topbar__set">
      <a class="topbar__item" href="https://maps.google.com/?q=We%C5%82niana+72,+54-061+Wroc%C5%82aw" target="_blank" rel="noopener">
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke-width="2" aria-hidden="true"><path d="M12 21s7-6.2 7-11a7 7 0 1 0-14 0c0 4.8 7 11 7 11z"/><circle cx="12" cy="10" r="2.6"/></svg>
        {ADDRESS}
      </a>
      <span class="topbar__item topbar__item--hours">
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5.2l3.4 2"/></svg>
        {HOURS_WEEK} · {HOURS_WEEKEND}
      </span>
    </div>
    <span class="topbar__note"><b>Serwis mobilny</b> • Wrocław i okolice</span>
  </div>
</div>
'''


NAV = [('uslugi', 'Usługi'), ('mobilny', 'Mobilny serwis'), ('proces', 'Jak to działa'),
       ('opinie', 'Opinie'), ('faq', 'FAQ'), ('kontakt', 'Kontakt')]


def header(r, active=''):
    links = ''.join(
        f'      <a class="nav__link{" is-active" if active == slug else ""}" href="{r}#{slug}">{label}</a>\n'
        for slug, label in NAV)
    return f'''
<header class="header">
  <div class="container">
    <a class="brand" href="{r or "/"}" aria-label="Dynamic AC — strona główna">
      <img class="brand__logo" src="{r}assets/img/logo.png" alt="Dynamic AC" width="900" height="328">
      <span class="brand__rule" aria-hidden="true"></span>
      <span class="brand__tag">Mobilny serwis klimatyzacji</span>
    </a>

    <nav class="nav" aria-label="Menu główne">
{links}    </nav>

    <div class="header__cta">
      <a class="header__phone" href="{TEL}">
        <span>Zadzwoń</span>
        <b>{PHONE}</b>
      </a>
      <a class="btn btn--primary btn--sm" href="#kontakt">Umów serwis</a>
      <button class="burger" type="button" aria-label="Otwórz menu" aria-expanded="false" aria-controls="drawer">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>
</header>
'''


def crumbs(r, trail):
    """trail: list of (href|None, label); the last item is the current page."""
    out = [f'<a href="{r or "/"}">Strona główna</a>']
    for href, label in trail:
        out.append('<span aria-hidden="true">›</span>')
        out.append(f'<a href="{href}">{e(label)}</a>' if href else f'<span>{e(label)}</span>')
    return '<nav class="crumbs" aria-label="Okruszki">' + ''.join(out) + '</nav>'


def cta_section(r, service=''):
    attr = f' data-service="{e(service)}"' if service else ''
    return f'''
  <section class="cta" id="kontakt">
    <img class="cta__bg" src="{r}assets/img/hero.jpg" alt="" aria-hidden="true" loading="lazy" width="1672" height="941">
    <div class="container">
      <div class="cta__copy">
        <h2 class="h2" data-reveal>Umów mobilny serwis<br class="br-desk"> klimatyzacji</h2>
        <p data-reveal>Zadzwoń i ustal dogodny termin oraz miejsce wykonania usługi. Odbieramy także po godzinach pracy warsztatów.</p>
        <div class="btn-row" data-reveal>
          <a class="btn btn--primary btn--lg" href="{TEL}">
            <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" aria-hidden="true"><path d="M4 5c0 8.3 6.7 15 15 15l1.5-3.4-4.3-2-2 2a12.6 12.6 0 0 1-6.8-6.8l2-2-2-4.3L4 5z"/></svg>
            Zadzwoń teraz
          </a>
          <a class="btn btn--ghost btn--lg" href="#k-imie">Zostaw kontakt</a>
        </div>
        <div class="cta__facts" data-reveal>
          <div><span>Telefon</span><b class="big"><a href="{TEL}">{PHONE}</a></b></div>
          <div><span>Adres</span><b>Wełniana 72<br>54-061 Wrocław</b></div>
          <div><span>Godziny</span><b>{HOURS_WEEK}<br>{HOURS_WEEKEND}</b></div>
        </div>
      </div>

      <div class="form-card" data-reveal>
        <div class="form-card__title">Zostaw kontakt</div>
        <p class="form-card__note">Oddzwaniamy zwykle w ciągu godziny w godzinach pracy.</p>
        <form class="lead-form" data-form="podstrona"{attr} novalidate>
          <div class="field">
            <label class="sr-only" for="k-imie">Imię</label>
            <input id="k-imie" name="imie" type="text" placeholder="Imię" autocomplete="given-name" required>
            <span class="field__err">Podaj imię, żebyśmy wiedzieli, jak się zwracać.</span>
          </div>
          <div class="field">
            <label class="sr-only" for="k-tel">Telefon</label>
            <input id="k-tel" name="telefon" type="tel" placeholder="Telefon" autocomplete="tel" inputmode="tel" required>
            <span class="field__err">Podaj numer telefonu (min. 9 cyfr).</span>
          </div>
          <div class="field">
            <label class="sr-only" for="k-auto">Model auta</label>
            <input id="k-auto" name="auto" type="text" placeholder="Model auta" autocomplete="off">
          </div>
          <div class="field">
            <label class="sr-only" for="k-msg">Opis problemu</label>
            <textarea id="k-msg" name="wiadomosc" rows="3" placeholder="Opis problemu — np. „słabo chłodzi od miesiąca”"></textarea>
          </div>
          <button class="btn btn--dark btn--submit" type="submit">Wyślij zapytanie</button>
          <p class="form-consent">Wysyłając formularz zgadzasz się na kontakt w sprawie zapytania. Danych nie przekazujemy dalej.</p>
        </form>
        <div class="form-success" hidden>
          <svg class="form-success__icon" viewBox="0 0 56 56" aria-hidden="true"><circle cx="28" cy="28" r="24"/><path d="M18 29l7 7 14-15"/></svg>
          <b>Dziękujemy!</b>
          <p>Zapytanie przyjęte — oddzwonimy pod podany numer. Jeśli sprawa jest pilna, zadzwoń: <a href="{TEL}">{PHONE}</a>.</p>
        </div>
      </div>
    </div>
  </section>
'''


def footer(r):
    svc = ''.join(f'          <li><a href="{r}{s["slug"]}/">{e(s["name"])}</a></li>\n' for s in SERVICES)
    return f'''
<footer class="footer">
  <div class="container">
    <div class="footer__top">
      <div class="footer__brand">
        <img src="{r}assets/img/logo-light.png" alt="Dynamic AC" width="900" height="328" loading="lazy">
        <p>Mobilny serwis klimatyzacji samochodowej. Wrocław i okolice — przyjeżdżamy tam, gdzie stoi Twoje auto.</p>
      </div>
      <div class="footer__col">
        <h4>Usługi</h4>
        <ul>
{svc}        </ul>
      </div>
      <div class="footer__col">
        <h4>Serwis</h4>
        <ul>
          <li><a href="{r}#mobilny">Mobilny serwis</a></li>
          <li><a href="{r}#proces">Jak to działa</a></li>
          <li><a href="{r}#opinie">Opinie</a></li>
          <li><a href="{r}blog/">Poradnik</a></li>
          <li><a href="{r}kontakt/">Kontakt</a></li>
        </ul>
      </div>
      <div class="footer__col">
        <h4>Kontakt</h4>
        <ul>
          <li><a href="{TEL}"><b>{PHONE}</b></a></li>
          <li><span>{ADDRESS}</span></li>
          <li><span>{HOURS_WEEK}</span></li>
          <li><span>{HOURS_WEEKEND}</span></li>
        </ul>
      </div>
    </div>
    <div class="footer__bottom">
      <span>© <span data-year>2026</span> {LEGAL} · NIP {NIP}</span>
      <div class="footer__legal">
        <a href="{r}kontakt/">Dane firmy</a>
        <a href="{r}#faq">FAQ</a>
      </div>
    </div>
  </div>
</footer>
'''


def floats(r, lightbox=False):
    lb = '''
<div class="lightbox" hidden>
  <button class="lightbox__close" type="button" aria-label="Zamknij">
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke-width="2" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg>
  </button>
  <img alt="">
</div>
''' if lightbox else ''
    return f'''
<div class="mbar">
  <a class="mbar__call" href="{TEL}">
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke-width="2" aria-hidden="true"><path d="M4 5c0 8.3 6.7 15 15 15l1.5-3.4-4.3-2-2 2a12.6 12.6 0 0 1-6.8-6.8l2-2-2-4.3L4 5z"/></svg>
    Zadzwoń
  </a>
  <a class="mbar__book" href="#kontakt">Umów serwis</a>
</div>

<div class="dock" aria-hidden="true">
  <a class="dock__call" href="{TEL}" tabindex="-1">
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#9FB3CC" stroke-width="2" aria-hidden="true"><path d="M4 5c0 8.3 6.7 15 15 15l1.5-3.4-4.3-2-2 2a12.6 12.6 0 0 1-6.8-6.8l2-2-2-4.3L4 5z"/></svg>
    {PHONE}
  </a>
  <a class="dock__book" href="#kontakt" tabindex="-1">Umów serwis</a>
</div>

<div class="drawer" id="drawer" aria-hidden="true">
  <div class="drawer__backdrop" data-close></div>
  <div class="drawer__panel" role="dialog" aria-modal="true" aria-label="Menu">
    <div class="drawer__top">
      <img src="{r}assets/img/logo-light.png" alt="Dynamic AC" width="900" height="328">
      <button class="drawer__close" type="button" aria-label="Zamknij menu" data-close>
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke-width="2" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg>
      </button>
    </div>
    <nav class="drawer__nav" aria-label="Menu mobilne">
      <a href="{r}#uslugi" data-close>Usługi</a>
      <a href="{r}#mobilny" data-close>Mobilny serwis</a>
      <a href="{r}#proces" data-close>Jak to działa</a>
      <a href="{r}#opinie" data-close>Opinie</a>
      <a href="{r}#faq" data-close>FAQ</a>
      <a href="{r}blog/">Poradnik</a>
      <a href="{r}kontakt/">Kontakt</a>
    </nav>
    <div class="drawer__foot">
      <a class="btn btn--primary btn--block" href="{TEL}">Zadzwoń: {PHONE}</a>
      <a class="btn btn--ghost btn--block" href="#kontakt" data-close>Umów serwis</a>
      <p class="drawer__meta">{ADDRESS}<br>{HOURS_WEEK} · {HOURS_WEEKEND}</p>
    </div>
  </div>
</div>
{lb}
<script src="{r}js/main.js" defer></script>
</body>
</html>
'''


# ------------------------------------------------------------- fragments ----

def phero(r, eyebrow, h1, lead, img, trail, highlights=None, extra_btn=None):
    hl = ''
    if highlights:
        cells = ''.join(
            f'''        <div class="hl">{icon(ic, 24)}<b>{e(t)}</b><span>{e(d)}</span></div>\n'''
            for ic, t, d in highlights)
        hl = f'      <div class="hl-grid" data-reveal>\n{cells}      </div>\n'
    second = extra_btn or f'<a class="btn btn--ghost btn--lg" href="#kontakt">Umów serwis</a>'
    return f'''
  <section class="phero">
    <img class="phero__bg" src="{r}assets/img/{img}" alt="" aria-hidden="true">
    <div class="container">
      {crumbs(r, trail)}
      <span class="eyebrow eyebrow--light">{e(eyebrow)}</span>
      <h1 class="h1" style="font-size:clamp(30px,3.6vw,52px)">{h1}</h1>
      <p class="phero__lead">{lead}</p>
      <div class="btn-row">
        <a class="btn btn--primary btn--lg" href="{TEL}">
          <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" aria-hidden="true"><path d="M4 5c0 8.3 6.7 15 15 15l1.5-3.4-4.3-2-2 2a12.6 12.6 0 0 1-6.8-6.8l2-2-2-4.3L4 5z"/></svg>
          Zadzwoń: {PHONE}
        </a>
        {second}
      </div>
{hl}    </div>
  </section>
'''


def entry(intro, sections):
    out = [f'        <p>{intro}</p>']
    for title, paras in sections:
        out.append(f'        <h2>{e(title)}</h2>')
        out += [f'        <p>{p}</p>' for p in paras]
    return '\n'.join(out)


def faq_details(items):
    return '\n'.join(
        f'        <details{" open" if i == 0 else ""}><summary>{e(q)}</summary><p>{a}</p></details>'
        for i, (q, a) in enumerate(items))


def steps_block(title, lead, steps):
    cards = ''
    for i, (ic, h, p) in enumerate(steps, 1):
        cards += f'''        <li class="step" data-reveal>
          <span class="step__ghost" aria-hidden="true">{i:02d}</span>
          <span class="step__icon">{icon(ic, 26)}</span>
          <div class="step__body">
            <span class="step__num">KROK {i:02d}</span>
            <h3>{e(h)}</h3>
            <p>{e(p)}</p>
          </div>
        </li>\n'''
    return f'''
  <section class="section section--tint">
    <div class="container">
      <div class="section-head" data-reveal>
        <div class="section-head__text"><h2 class="h2">{e(title)}</h2></div>
        <p class="section-head__aside">{e(lead)}</p>
      </div>
      <ol class="steps">
{cards}      </ol>
    </div>
  </section>
'''


def gallery_block(r, imgs, alts):
    items = ''.join(
        f'''        <button class="gallery__item" type="button" data-full="{r}assets/img/{img}" aria-label="Powiększ zdjęcie">
          <img src="{r}assets/img/{img.replace(".jpg", "-sm.jpg") if (ROOT / "assets/img" / img.replace(".jpg", "-sm.jpg")).exists() else img}" alt="{e(alt)}" loading="lazy">
        </button>\n'''
        for img, alt in zip(imgs, alts))
    return f'''
  <section class="section">
    <div class="container">
      <div class="section-head" data-reveal>
        <div class="section-head__text">
          <span class="eyebrow">Realizacje</span>
          <h2 class="h2">Tak wygląda nasza praca</h2>
        </div>
        <p class="section-head__aside">Zdjęcia z obsługi wykonywanej u klientów we Wrocławiu.</p>
      </div>
      <div class="gallery" data-reveal>
{items}      </div>
    </div>
  </section>
'''


def xlinks_block(r, current_slug):
    cards = ''
    for s in SERVICES:
        if s['slug'] == current_slug:
            continue
        cards += f'''        <a class="xlink" href="{r}{s["slug"]}/">
          <span>{s["num"]}</span>
          <b>{e(s["name"])}</b>
          <p>{e(s["short"])}</p>
        </a>\n'''
    return f'''
  <section class="section section--tint">
    <div class="container">
      <div class="section-head" data-reveal>
        <div class="section-head__text"><h2 class="h2">Pozostałe usługi</h2></div>
      </div>
      <div class="xlinks" data-reveal>
{cards}      </div>
    </div>
  </section>
'''


# ------------------------------------------------------------ page types ----

def build_service(s):
    r = '../'
    ld_service = {
        '@context': 'https://schema.org', '@type': 'Service',
        'name': s['name'], 'serviceType': s['name'], 'description': s['desc'],
        'areaServed': {'@type': 'City', 'name': 'Wrocław'},
        'provider': dict(BUSINESS, **{'@context': 'https://schema.org'}),
        'url': f'{SITE}/{s["slug"]}/',
    }
    ld_faq = {
        '@context': 'https://schema.org', '@type': 'FAQPage',
        'mainEntity': [{'@type': 'Question', 'name': q,
                        'acceptedAnswer': {'@type': 'Answer', 'text': html.unescape(
                            __import__('re').sub('<[^>]+>', '', a))}}
                       for q, a in s['faq']],
    }
    ld_crumbs = {
        '@context': 'https://schema.org', '@type': 'BreadcrumbList',
        'itemListElement': [
            {'@type': 'ListItem', 'position': 1, 'name': 'Strona główna', 'item': SITE + '/'},
            {'@type': 'ListItem', 'position': 2, 'name': 'Usługi', 'item': SITE + '/#uslugi'},
            {'@type': 'ListItem', 'position': 3, 'name': s['name'], 'item': f'{SITE}/{s["slug"]}/'},
        ],
    }

    alts = [f'{s["name"]} — mobilny serwis Dynamic AC we Wrocławiu ({i})' for i in (1, 2, 3)]

    html_out = head(r, s['title'], s['desc'], f'{SITE}/assets/img/{s["hero_img"]}',
                    [ld_service, ld_faq, ld_crumbs],
                    preload=f'{r}assets/img/{s["hero_img"]}', canonical=f'{s["slug"]}/')
    html_out += topbar()
    html_out += header(r, 'uslugi')
    html_out += '\n<main id="main">\n'
    html_out += phero(r, s['pill'], s['h1'], e(s['lead']), s['hero_img'],
                      [(r + '#uslugi', 'Usługi'), (None, s['name'])], s['highlights'])

    html_out += f'''
  <section class="section">
    <div class="container">
      <div class="article">
        <div class="entry-content">
{entry(s['intro'], s['sections'])}
        <h2>Najczęstsze pytania</h2>
{faq_details(s['faq'])}
        </div>

        <aside>
          <div class="toc">
            <div class="toc__title">Na tej stronie</div>
            <nav data-toc aria-label="Spis treści"></nav>
          </div>
          <div class="aside-cta">
            <b>Umów {e(s['cta'])}</b>
            <p>Przyjeżdżamy pod dom, biuro albo na parking. Dojazd w obrębie Wrocławia w cenie usługi.</p>
            <a class="btn btn--primary btn--sm" href="{TEL}">Zadzwoń: {PHONE}</a>
            <a class="btn btn--outline btn--sm" href="#kontakt">Zostaw kontakt</a>
          </div>
        </aside>
      </div>
    </div>
  </section>
'''
    html_out += steps_block(s['steps_title'], s['steps_lead'], s['steps'])
    html_out += gallery_block(r, s['gallery'], alts)
    html_out += xlinks_block(r, s['slug'])
    html_out += cta_section(r, s['name'])
    html_out += '\n</main>\n'
    html_out += footer(r)
    html_out += floats(r, lightbox=True)
    return html_out


def render_body(blocks):
    out = []
    for kind, val in blocks:
        if kind == 'h2':
            out.append(f'        <h2>{e(val)}</h2>')
        elif kind == 'p':
            out.append(f'        <p>{val}</p>')
        elif kind == 'ul':
            lis = ''.join(f'<li>{e(x)}</li>' for x in val)
            out.append(f'        <ul>{lis}</ul>')
        elif kind == 'ol':
            lis = ''.join(f'<li>{e(x)}</li>' for x in val)
            out.append(f'        <ol>{lis}</ol>')
        elif kind == 'callout':
            paras = ''.join(f'<p>{e(x)}</p>' for x in val)
            out.append(f'        <div class="callout">{paras}</div>')
    return '\n'.join(out)


def build_post(p):
    r = '../../'
    from content_services import SERVICE_BY_SLUG
    svc = SERVICE_BY_SLUG[p['service']]
    ld = {
        '@context': 'https://schema.org', '@type': 'BlogPosting',
        'headline': p['title'], 'description': p['excerpt'], 'datePublished': p['date'],
        'image': f'{SITE}/assets/img/{p["img"]}', 'inLanguage': 'pl-PL',
        'mainEntityOfPage': f'{SITE}/blog/{p["slug"]}/',
        'author': {'@type': 'Organization', 'name': 'Dynamic AC'},
        'publisher': {'@type': 'Organization', 'name': 'Dynamic AC'},
    }
    ld_crumbs = {
        '@context': 'https://schema.org', '@type': 'BreadcrumbList',
        'itemListElement': [
            {'@type': 'ListItem', 'position': 1, 'name': 'Strona główna', 'item': SITE + '/'},
            {'@type': 'ListItem', 'position': 2, 'name': 'Poradnik', 'item': SITE + '/blog/'},
            {'@type': 'ListItem', 'position': 3, 'name': p['title'], 'item': f'{SITE}/blog/{p["slug"]}/'},
        ],
    }

    out = head(r, f'{p.get("seo_title", p["title"])} | Dynamic AC', p['excerpt'], f'{SITE}/assets/img/{p["img"]}',
               [ld, ld_crumbs], preload=f'{r}assets/img/{p["img"]}', canonical=f'blog/{p["slug"]}/')
    out += topbar()
    out += header(r)
    out += '\n<main id="main">\n'
    out += f'''
  <section class="phero">
    <img class="phero__bg" src="{r}assets/img/{p["img"]}" alt="" aria-hidden="true">
    <div class="container">
      {crumbs(r, [(r + 'blog/', 'Poradnik'), (None, p['title'])])}
      <span class="eyebrow eyebrow--light">{e(p["cat"])}</span>
      <h1 class="h1" style="font-size:clamp(28px,3.4vw,48px)">{e(p["title"])}</h1>
      <p class="phero__lead">{e(p["lead"])}</p>
      <div class="post-meta" style="color:#7D8899">
        <i style="color:#FF8A4C">{e(p["cat"])}</i><em aria-hidden="true"></em>
        <time datetime="{p["date"]}">{p["date_pl"]}</time><em aria-hidden="true"></em>
        <span>{p["read"]} czytania</span>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <div class="article">
        <div class="entry-content">
{render_body(p["body"])}
          <div class="share-row">
            <span>Przydatne? Podeślij komuś, komu też się przyda.</span>
            <button class="btn btn--share" type="button" data-share>Kopiuj link</button>
          </div>
        </div>

        <aside>
          <div class="toc">
            <div class="toc__title">Na tej stronie</div>
            <nav data-toc aria-label="Spis treści"></nav>
          </div>
          <div class="aside-cta">
            <b>Powiązana usługa</b>
            <p>{e(svc["short"])}</p>
            <a class="btn btn--outline btn--sm" href="{r}{svc["slug"]}/">{e(svc["name"])}</a>
            <a class="btn btn--primary btn--sm" href="{TEL}">Zadzwoń: {PHONE}</a>
          </div>
        </aside>
      </div>
    </div>
  </section>
'''
    others = [q for q in POSTS if q['slug'] != p['slug']]
    if others:
        cards = ''.join(f'''        <a class="post-card" href="{r}blog/{q["slug"]}/">
          <div class="post-card__media"><img src="{r}assets/img/{q["img"]}" alt="" loading="lazy"></div>
          <div class="post-card__body">
            <div class="post-meta"><i>{e(q["cat"])}</i><em aria-hidden="true"></em><span>{q["read"]}</span></div>
            <h3>{e(q["title"])}</h3>
            <p>{e(q["excerpt"])}</p>
          </div>
        </a>\n''' for q in others)
        out += f'''
  <section class="section section--tint">
    <div class="container">
      <div class="section-head" data-reveal>
        <div class="section-head__text"><h2 class="h2">Przeczytaj także</h2></div>
      </div>
      <div class="post-grid" data-reveal>
{cards}      </div>
    </div>
  </section>
'''
    out += cta_section(r)
    out += '\n</main>\n'
    out += footer(r)
    out += floats(r)
    return out


def build_blog_index():
    r = '../'
    first, rest = POSTS[0], POSTS[1:]
    ld = {
        '@context': 'https://schema.org', '@type': 'Blog',
        'name': 'Poradnik Dynamic AC', 'url': f'{SITE}/blog/',
        'blogPost': [{'@type': 'BlogPosting', 'headline': p['title'], 'datePublished': p['date'],
                      'url': f'{SITE}/blog/{p["slug"]}/'} for p in POSTS],
    }
    out = head(r, 'Poradnik — klimatyzacja samochodowa | Dynamic AC',
               'Praktyczne artykuły o klimatyzacji samochodowej: jak często robić przegląd, dlaczego klimatyzacja '
               'słabo chłodzi i skąd bierze się zapach z nawiewów.',
               f'{SITE}/assets/img/{first["img"]}', [ld], canonical='blog/')
    out += topbar()
    out += header(r)
    out += '\n<main id="main">\n'
    out += f'''
  <section class="phero">
    <img class="phero__bg" src="{r}assets/img/diagnostyka.jpg" alt="" aria-hidden="true">
    <div class="container">
      {crumbs(r, [(None, 'Poradnik')])}
      <span class="eyebrow eyebrow--light">Poradnik</span>
      <h1 class="h1" style="font-size:clamp(30px,3.6vw,52px)">Klimatyzacja samochodowa<br class="br-desk"> bez zgadywania</h1>
      <p class="phero__lead">Konkretne odpowiedzi na pytania, które najczęściej słyszymy przez telefon — napisane tak,
      żeby dało się z nich skorzystać także bez naszej pomocy.</p>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <a class="post-feature" href="{r}blog/{first["slug"]}/" data-reveal>
        <div class="post-feature__media"><img src="{r}assets/img/{first["img"]}" alt="" loading="lazy"></div>
        <div class="post-feature__body">
          <div class="post-meta"><i>{e(first["cat"])}</i><em aria-hidden="true"></em><time datetime="{first["date"]}">{first["date_pl"]}</time><em aria-hidden="true"></em><span>{first["read"]}</span></div>
          <h2>{e(first["title"])}</h2>
          <p>{e(first["excerpt"])}</p>
          <span class="svc__more" style="position:static">Czytaj dalej
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6"/></svg>
          </span>
        </div>
      </a>

      <div class="post-grid" data-reveal>
'''
    for q in rest:
        out += f'''        <a class="post-card" href="{r}blog/{q["slug"]}/">
          <div class="post-card__media"><img src="{r}assets/img/{q["img"]}" alt="" loading="lazy"></div>
          <div class="post-card__body">
            <div class="post-meta"><i>{e(q["cat"])}</i><em aria-hidden="true"></em><time datetime="{q["date"]}">{q["date_pl"]}</time><em aria-hidden="true"></em><span>{q["read"]}</span></div>
            <h3>{e(q["title"])}</h3>
            <p>{e(q["excerpt"])}</p>
          </div>
        </a>\n'''
    for t in UPCOMING[:1]:
        out += f'''        <div class="post-card post-card--soon">
          <div class="post-card__media"><img src="{r}assets/img/van-sm.jpg" alt="" loading="lazy"></div>
          <div class="post-card__body">
            <div class="post-meta"><i>Wkrótce</i></div>
            <h3>{e(t)}</h3>
            <p>Artykuł w przygotowaniu.</p>
          </div>
        </div>\n'''
    out += '''      </div>
    </div>
  </section>
'''
    out += cta_section(r)
    out += '\n</main>\n'
    out += footer(r)
    out += floats(r)
    return out


def build_contact():
    r = '../'
    ld = dict(BUSINESS, **{
        '@context': 'https://schema.org', 'url': f'{SITE}/kontakt/',
        'openingHoursSpecification': [
            {'@type': 'OpeningHoursSpecification',
             'dayOfWeek': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
             'opens': '08:00', 'closes': '20:00'},
            {'@type': 'OpeningHoursSpecification', 'dayOfWeek': ['Saturday', 'Sunday'],
             'opens': '09:00', 'closes': '17:00'},
        ],
    })
    ld_crumbs = {
        '@context': 'https://schema.org', '@type': 'BreadcrumbList',
        'itemListElement': [
            {'@type': 'ListItem', 'position': 1, 'name': 'Strona główna', 'item': SITE + '/'},
            {'@type': 'ListItem', 'position': 2, 'name': 'Kontakt', 'item': f'{SITE}/kontakt/'},
        ],
    }
    out = head(r, 'Kontakt — Dynamic AC, mobilny serwis klimatyzacji Wrocław',
               f'Dynamic AC — {ADDRESS}. Telefon {PHONE}. {HOURS_WEEK}, {HOURS_WEEKEND}. '
               f'Dane firmy: {LEGAL}, NIP {NIP}, REGON {REGON}.',
               f'{SITE}/assets/img/van.jpg', [ld, ld_crumbs], canonical='kontakt/')
    out += topbar()
    out += header(r, 'kontakt')
    out += '\n<main id="main">\n'
    out += phero(r, 'Kontakt', 'Zadzwoń albo napisz —<br class="br-desk"> przyjedziemy do auta',
                 'Najszybszą drogą jest telefon: zwykle już podczas rozmowy wiemy, czego szukać, '
                 'i umawiamy konkretną godzinę.', 'van.jpg', [(None, 'Kontakt')])
    out += f'''
  <section class="section">
    <div class="container">
      <div class="contact-grid" data-reveal>
        <div class="contact-cell">
          <div class="contact-row">
            {icon('phone', 24)}
            <div><span>Telefon</span><b><a href="{TEL}">{PHONE}</a></b></div>
          </div>
          <div class="contact-row">
            {icon('pin', 24)}
            <div><span>Adres serwisu</span><b>{ADDRESS}</b></div>
          </div>
          <div class="contact-row">
            {icon('clock', 24)}
            <div><span>Godziny pracy</span><b>{HOURS_WEEK}<br>{HOURS_WEEKEND}</b></div>
          </div>
          <div class="contact-row">
            {icon('van', 24)}
            <div><span>Obszar działania</span><b>Wrocław i okolice</b></div>
          </div>
        </div>

        <div class="contact-cell">
          <div class="contact-row">
            {icon('doc', 24)}
            <div>
              <span>Dane firmy</span>
              <p class="contact-legal" style="margin-top:6px">
                <b>{LEGAL}</b><br>
                NIP: {NIP}<br>
                REGON: {REGON}<br>
                Adres rejestrowy: {REG_ADDRESS}
              </p>
            </div>
          </div>
          <div class="contact-row">
            {icon('search', 24)}
            <div>
              <span>Zanim zadzwonisz</span>
              <p class="contact-legal" style="margin-top:6px">
                Przygotuj markę, model i rocznik auta oraz krótki opis objawu — czy chłodzenie
                pogarszało się stopniowo, czy zniknęło nagle. To dwie informacje, które najbardziej
                skracają diagnostykę.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="map-wrap" data-reveal style="margin-top:24px">
        <iframe
          title="Mapa: Wełniana 72, 54-061 Wrocław"
          src="https://www.openstreetmap.org/export/embed.html?bbox=16.8830%2C51.1505%2C16.9230%2C51.1705&amp;layer=mapnik&amp;marker=51.16051%2C16.90299"
          loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
      <p class="lead lead--sm" style="margin-top:14px">
        <a class="map-link" href="https://maps.google.com/?q=We%C5%82niana+72,+54-061+Wroc%C5%82aw" target="_blank" rel="noopener">Otwórz w Mapach Google →</a>
      </p>
    </div>
  </section>
'''
    out += xlinks_block(r, '')
    out += cta_section(r)
    out += '\n</main>\n'
    out += footer(r)
    out += floats(r)
    return out


# ------------------------------------------------------------------ main ----

def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')
    print(f'  {path.relative_to(ROOT.parent)}  ({len(content) // 1024} KB)')


def main():
    print('Dynamic AC — building sub-pages')
    for s in SERVICES:
        write(ROOT / s['slug'] / 'index.html', build_service(s))
    write(ROOT / 'kontakt' / 'index.html', build_contact())
    write(ROOT / 'blog' / 'index.html', build_blog_index())
    for p in POSTS:
        write(ROOT / 'blog' / p['slug'] / 'index.html', build_post(p))
    print('done.')


if __name__ == '__main__':
    main()
